name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: source
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Build Jekyll site
      run: |
        set -xo pipefail
        cd docs
        rm -rf _site/*
        gem install bundler
        bundle install
        bundle exec jekyll build
        cd ..
        # cp CNAME _site/CNAME
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        set -xo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout gh-pages
        ls -Q | grep -v docs/_site | xargs rm -rf
        mv docs/_site/* .
        rm -rf docs/_site
        rm -rf .jekyll-cache
        [[ -n "$(git status --porcelain)" ]] || exit 0
        git add .
        git commit -m "Build $(git rev-parse source | grep -o '^.\{10\}')"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
